### ISSUE TITLE
Code completion and navigation for function names

### ISSUE THREAD

**Issue by trinhanhngoc** [odoo-ide/vscode-odoo#53]
- [x] [`fields.Field(compute="...")`](https://github.com/odoo-ide/vscode-odoo/issues/16)
- [x] [`fields.Field(inverse="...")`](https://github.com/odoo-ide/vscode-odoo/issues/16)
- [x] [`fields.Field(search="...")`](https://github.com/odoo-ide/vscode-odoo/issues/16)
- [ ] `fields.Field(group_expand="...")`
- [ ] `BaseModel._patch_method(...)`
- [ ] `BaseModel._revert_method(...)`
- [ ] Manifest attributes: `pre_init_hook`, `post_init_hook`, `uninstall_hook`, `post_load`
