### ISSUE TITLE
Code completion and navigation for model names

### ISSUE THREAD

**Issue by trinhanhngoc** [odoo-ide/vscode-odoo#56]
- [x] Model attribute [`_inherit = '...'`](https://github.com/odoo-ide/vscode-odoo/issues/3)
- [x] Model attribute [`_inherits = {'...': }`](https://github.com/odoo-ide/vscode-odoo/issues/3)
- [x] Model attribute `_depends = {'...': }`
- [x] Relational field attribute [`fields.One2many('...')`](https://github.com/odoo-ide/vscode-odoo/issues/3)
- [x] [`Environment['...']`](https://github.com/odoo-ide/vscode-odoo/issues/12)
- [x] `Registry['...']`
- [x] Action values `{'res_model': '...'}`
- [x] Field attribute `default_model='...'` in `res.config.settings`
- [x] `context.get('active_model') == '...'`
- [x] Calendar view `<field write_model='...'`
- [x] Action window record `<field name="res_model">...</field>'`
